apiVersion: apps/v1
kind: Deployment
metadata:
  name: holiday-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holiday-challenge
  template:
    metadata:
      labels:
        app: holiday-challenge
    spec:
      containers:
        - name: holiday-challenge
          image: ghcr.io/mariusdkm/holiday_challenge:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: POSTGRES_USER
              value: ...
            - name: POSTGRES_PASSWORD
              value: ...
            - name: POSTGRES_DB
              value: ...
            - name: DATABASE_URL
              value: ...
            - name: REDIS_URL
              value: ...
---
kind: Service
apiVersion: v1
metadata:
  name: holiday-challenge-service
spec:
  selector:
    app: holiday-challenge
  ports:
    - port: 3000 # Default port for image