services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"

  svelte:
    build:
      context: .
      dockerfile: Dockerfile
#    image: ghcr.io/mariusdkm/holiday_challenge:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
