// export const departureAirports = {
//   'Amsterdam': 'AMS',
//   'Berlin': 'BER',
//   'Billund': 'BLL',
//   'Bremen': 'BRE',
//   'Berne': 'BRN',
//   'Brussels': 'BRU',
//   'Base': 'BSL',
//   'Cologne': 'CGN',
//   'Brussels South': 'CRL',
//   'Magdeburg-Cochstedt': 'CSO',
//   'Dresden': 'DRS',
//   'Dortmund': 'DTM',
//   'Düsseldorf': 'DUS',
//   'Eindoven': 'EIN',
//   'Erfurt': 'ERF',
//   'Friedrichshafen': 'FDH',
//   'Karlsruhe-Baden - Soellingen': 'FKB',
//   'Memmingen': 'FMM',
//   'Münster/Osnabrück': 'FMO',
//   'Frankfurt Main': 'FRA',
//   'Graz': 'GRZ',
//   'Geneva': 'GVA',
//   'Westerland, Sylt': 'GWT',
//   'Hannover': 'HAJ',
//   'Hamburg': 'HAM',
//   'Frankfurt Hahn': 'HHN',
//   'Innsbruck': 'INN',
//   'Klagenfurt': 'KLU',
//   'Krakow': 'KRK',
//   'Kassel': 'KSF',
//   'Lübeck': 'LBC',
//   'Leipzig': 'LEJ',
//   'Linz': 'LNZ',
//   'Luxembourg': 'LUX',
//   'München': 'MUC',
//   'Weeze': 'NRN',
//   'Nürnberg': 'NUE',
//   'Paderborn Lippstadt': 'PAD',
//   'Prague': 'PRG',
//   'Rostock-Laage': 'RLG',
//   'Rotterdam': 'RTM',
//   'Saarbrücken': 'SCN',
//   'Stuttgart': 'STR',
//   'Strasbourg': 'SXB',
//   'Salzburg': 'SZG',
//   'Wien (Vienna)': 'VIE',
//   'Warsaw': 'WAW',
//   'Zürich': 'ZRH'
// };

export const arrivalAirportOptions = {
  'PMI': 'Mallorca'
};

export const departureAirportOptions = {
  'AMS': 'Amsterdam',
  'BER': 'Berlin',
  'BLL': 'Billund',
  'BRE': 'Bremen',
  'BRN': 'Berne',
  'BRU': 'Brussels',
  'BSL': 'Base',
  'CGN': 'Cologne',
  'CRL': 'Brussels South',
  'CSO': 'Magdeburg-Cochstedt',
  'DRS': 'Dresden',
  'DTM': 'Dortmund',
  'DUS': 'Düsseldorf',
  'EIN': 'Eindoven',
  'ERF': 'Erfurt',
  'FDH': 'Friedrichshafen',
  'FKB': 'Karlsruhe-Baden - Soellingen',
  'FMM': 'Memmingen',
  'FMO': 'Münster/Osnabrück',
  'FRA': 'Frankfurt Main',
  'GRZ': 'Graz',
  'GVA': 'Geneva',
  'GWT': 'Westerland, Sylt',
  'HAJ': 'Hannover',
  'HAM': 'Hamburg',
  'HHN': 'Frankfurt Hahn',
  'INN': 'Innsbruck',
  'KLU': 'Klagenfurt',
  'KRK': 'Krakow',
  'KSF': 'Kassel',
  'LBC': 'Lübeck',
  'LEJ': 'Leipzig',
  'LNZ': 'Linz',
  'LUX': 'Luxembourg',
  'MUC': 'München',
  'NRN': 'Weeze',
  'NUE': 'Nürnberg',
  'PAD': 'Paderborn Lippstadt',
  'PRG': 'Prague',
  'RLG': 'Rostock-Laage',
  'RTM': 'Rotterdam',
  'SCN': 'Saarbrücken',
  'STR': 'Stuttgart',
  'SXB': 'Strasbourg',
  'SZG': 'Salzburg',
  'VIE': 'Wien (Vienna)',
  'WAW': 'Warsaw',
  'ZRH': 'Zürich'
};